### ISSUE TITLE
Maybe remove localhost links and add description of RStudio Server link location in Readme

### ISSUE THREAD

**Issue by schloerke** [rstudio/plumber#269]
The links cause false positive errors when checking the package.  While the links make sense in context of the example, they are technically broken as they don't exist if the example isn't being run.  

Thoughts for going forward?

**Comment by schloerke** [comment]
My thought is to remove them as it makes a very clean package submission.  However, it worked just fine in v0.4.6.

**Comment by trestletech** [comment]
Yeah, it's a catch-22 to me. I like having them to cover the 90% case of helping people get started, but the URLs are wrong for folks running via RStudio Server. So it could create confusion (and difficulty submitting to CRAN).

**Comment by schloerke** [comment]
What is the link for RStudio Server?  

I'd be happy to keep the link as inline code and add a inline code link for RStudio server, but never insert the html link.

Ex:

---------------------------------------------------------------------------

readme readme readme `http://localhost:8000` (RStudio Server link: `http://localhost:8001`) more readme readme readme

**Comment by trestletech** [comment]
Well the problem is it's not deterministic. Localhost works if you're running your R session locally. But if you're running on RStudio Server, it may be `rstudio.cloud/someSessionId/` or `rstudio.mycompany.org:4141/` or who knows what else. In that case it would have to be "look at the hostname in the browser bar and use that"

It seemed like that was a minority case and that the average person using RStudio Server tends to understand that they're not running on `localhost`, but I'm sure it's tripped someone up.

**Comment by schloerke** [comment]
I think it's fair to explain that one as it's soooo different.  Might be better addressed in a separate paragraph at the end, but have the examples all use `localhost:8000`.
