### ISSUE TITLE
Return content-type with filename

### ISSUE THREAD

**Issue by aleDsz** [rstudio/plumber#287]
Hi,

I'm using the serializer with contentType to return a CSV. But my customer asked me for return this CSV with a file name, but i didn't find anything about returning with a filename, using plumber package.

```
#* @serializer contentType list(type="text/csv")
#* @get /get_report
api.get_report <- function (req) {
    [...]
}
```

There's a way to do that, or this feature is in the dev pipeline?

Thanks,
aleDsz.

**Comment by schloerke** [comment]
Is the goal to:
* return only a file name
* return only csv content
* return both the file name and csv content
?

------------------------

If you need the file name as well as the content, from the user's perspective, it should be a dynamic route that is resolved with `api.get_report`.  
```r
#* @serializer contentType list(type="text/csv")
#* @get /get_report/<file_name>.csv
api.get_report <- function (file_name) {
    [...]
# return csv content
}
```

If I visited `/get_report/my_file.csv` I could save the content as is (with `.csv` in the url).

Does this answer your question?

**Comment by ssword** [comment]
`#* @serializer contentType list(type="text/csv")
#* @get /get_report/
api.get_report <- function (file_name) {
  # This header is a convention that instructs browsers to present the response
  # as a download named filename rather than trying to render it inline.
  attachmentString = paste0("attachment; filename=", filename)
  
  res$setHeader("Content-Disposition", attachmentString)
  
  # Read in the raw contents of the binary file
  bin <- readBin(outputfile, "raw", n=file.info(outputfile)$size)
  
  #Return the binary contents
  bin
}`

Maybe like this? It will return the file with specific name, meanwhile, have file name information in the header.

**Comment by trestletech** [comment]
Example docs proposed here: https://github.com/trestletech/apis-plumber/pull/14/files

**Comment by rensa** [comment]
I can see that it's possible to add a custom or dynamically generated default file name for downloads by setting the bypassing serialization (ie. by doing the serialization work, like setting the headers and body, in the endpoint) and returning the response object.

But I can see that image serializers (`png` and `jpeg`) accept custom arguments, like `width` and `height`. It'd be great if I could do the same for my own serializers. Is it possible to do so and either:

* access such arguments in my decorated endpoint comments (eg. `@csv (file_basename = "mydownload")`), or
* to pass such arguments to the serializer when wrapping my endpoint, so that i can have them dynamically reflect inputs or processing done by the endpoint?

The second scenario is particularly attractive to me—my users request a CSV file from an endpoint based on a number of input arguments, and it would be great if the CSV served to them had a default file name reflecting those inputs.
