### ISSUE TITLE
postBodyFilter show warnings when binary files are POSTed

### ISSUE THREAD

**Issue by battmanux** [rstudio/plumber#359]
https://github.com/trestletech/plumber/blob/cccfeae55865b7dcece27a8a7e2b77cd3d5d09b1/R/post-body.R#L4

We try to upload jpeg or png using an @post hook.
We could not find examples bu finally ended up with : 
```r
#* PostImage 
#* @param id image Id
#* @post .*/api/<id>/image
function(req, id){

  l_fname <- paste0("data/images/",id,".jpg", sep = "")
  # cat("target: ", l_fname, "\n")
  
  req$rook.input$rewind()
  writeBin(req$rook.input$read(), l_fname)
  
  "OK"
}
```

1/ I was expecting a simpler way. Maybe adding a generic filter to fill a req$postBodyBinary
2/ When POSTed  body contains binaries (and may be the case for PUT too), body parsing tries to split lined and throw useless warnings.  req$.internal$postBodyHandled should be aware that we expect binary for this url. 

Maybe you could add @binary_post to be set instead of @post: 

```r
#* @binary_post /my_location/<name>
function(...)
```

Regards,

Emmanuel

**Comment by jcpsantiago** [comment]
I also had to go the  `rook.input` route when adding support for Protocol Buffers. Having a way to disable parsing the body into strings would help save resources.

**Comment by schloerke** [comment]
I'd really like to have an "opt in" for the filters, rather than a "stop processing up to this filter" setup.  This would easily fix this situation, rather than making it convoluted.

You could add a preempt: `#' @preempt postBody`, which will not attempt to process the `postBody` filter. This also currently remove any other filter that you've added, the `cookieParser` filter, and `sharedSecrete` filter.

@battmanux Please let me know how this works out for you.

**Comment by schloerke** [comment]
Plumber body parsing has been overhauled in v1.0.0. 

Closing
