### ISSUE TITLE
Support arrays as query parameters

### ISSUE THREAD

**Issue by mattyb** [rstudio/plumber#516]
Standard libraries construct array query parameters as below:
```
http://hostname/endpoint?colors[]=blue&colors[]=green
```

If plumber sees this for an endpoint with a `colors` parameter, it should construct a list and pass it to the function.

**Comment by meztez** [comment]
What you propose would not be supported by OpenApi standard.
See https://swagger.io/docs/specification/serialization/ and https://stackoverflow.com/questions/11490326/is-array-syntax-using-square-brackets-in-url-query-strings-valid

But something could be done by defining plumber param as 
```
#* @param number:numeric[] a numeric array
```

Since it is supported in OpenApi, I'll look into how that could be done.
