### ISSUE TITLE
R Plumber performance on different OSs

### ISSUE THREAD

**Issue by Halberdier** [rstudio/plumber#795]
I experienced the following behavior that I cannot explain.

I wrote an R API server with plumber. The APIs are defined in a servdef.R script with the plumber #* annotations. Typically a client sends a POST with parameters, the server performs some complex calculations and sends back the result. Then I wrote a short script servlaunch.R to launch it:
```
library(plumber)
plserv <- plumb('servdef.R')
plserv$run(host = '0.0.0.0', port = 8000)
```
I call the launcher on either Windows 10 or Linux servers with Rscript servlaunch.R.

On Windows, it can be stopped with a single ctrl-C hit. A performance test from a client, calling one API 100 times, shows a constant response time of about 200ms all the 100 times.

On Linux, it needs two ctrl-C hits to be stopped. I read that in Unix-like systems it's normal that the first ctrl-C sends a SIGINT that only cleans variables, without stopping the process. The performance test shows a degradation during the 100 API calls, responding within around 400ms at the beginning and 1200ms at the end. However, after the first ctrl-C the server is still alive and launching the performance test then, it behaves like in Windows, 200ms with no degradation.

I couldn't come out with anything better than wrapping the launch in a shell script:
```
Rscript servlaunch.R &
SL_PID=$!
sleep 1
kill -INT $SL_PID
```
with the last command simulating the first ctrl-C.

I posted it as [question](https://stackoverflow.com/questions/67122798/r-plumber-performance-on-different-oss) on Stack Overflow.

**Comment by meztez** [comment]
@Halberdier Without knowing what your API does, it's going to be hard to reprex.

**Comment by atheriel** [comment]
A couple suggestions on benchmarking:

* Figure out how fast your server needs to be. If you're only expecting one request per minute, 1200ms does not matter. If you are expecting 10 requests per second, then even 200ms is much too slow to meet demand with a single process.

* Try benchmarking the underlying R code (e.g. without all the Plumber stuff) on Linux and Windows to see if it is the actual workload that is the source of the issue.

* Instead of "calling one API 100 times", use a proper API load testing tool. The [`loadtest`](https://github.com/tmobile/loadtest) package might be a good choice.

Finally, if the issue is that initial requests start out fast but the API gets slower over time, there are two likely causes: (1) your server gets progressively overloaded as it queues up more requests; or (2) your workload is not independent for individual requests.

I'll observe that the overhead of Plumber itself is about 1-2 milliseconds per request, so this is mostly going to be about your actual workload.

**Comment by Halberdier** [comment]
Hi, thank you for the tips!
Following @meztez comment, I thought that it would be needlessly complex to refer to my actual full APIs, so I tried to reproduce the issue on something simpler. This led me to further isolate the problem, which turned out to be linked with the `gsubfn` package, which I'm using for elementwise list assignments in a single command.
I benchmarked in several combinations, and the issue occurs only in Linux with both plumber and gsubfn, all the three elements must be present.
Thus I believe that the straightforward solution would just be avoiding to load the `gsubfn` library and accepting a more verbose code.
Anyway, I think it can be interesting to investigate further on the behavior of plumber in conjunction with gsubfn, so I will try to finalize the simpler example. Please let me know if you prefer to close the thread now or wait for some more findings.

**Comment by Halberdier** [comment]
I couldn't replicate the performance issue with a simple piece of code so far.
However launching any plumber server that loads the gsubfn library on a Unix-like system requires two ctrl-C to be stopped, instead of just one. I think this is a sufficient oddity to raise an alert, but I also believe that this is more specific to gsubfn than to plumber.
I will close the issue here. Maybe I will open it again, but on the gsubfn git pages.
Thank you for your support!
